sudo: true
dist: bionic
language: generic
cache: apt

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/texlive'
    packages:
      - wget
      - tree
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-lang-german
      - texlive-science
      - texlive-bibtex-extra
      - lmodern
      - latexmk
      - biber
      - gnuplot
      - make
      
before_install:
  - wget 'https://packages.oth-regensburg.de/ctan/macros/latex/contrib/IEEEtran/tools/IEEEtrantools.sty'
  - chmod +x .travis/git-info-2.sh
  - ".travis/git-info-2.sh"

env:
    - TEXINPUTS='LatexPackages//:'

script:
    - make full
    - mkdir dist
    - mv full.pdf dist/2022_ADM2.pdf
    - mv full.log dist/2022_ADM2.log
    - cd dist/
    - tree -H '.' -I "index.html" -D --charset utf-8 -T "Discrete Optimization" > index.html

deploy:
    - provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      local-dir: dist/
      keep-history: false
      on:
        branch: master