name: Make and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Handle prerequisites
      run: make before-install
      
    - name: Install packages
      run: make install-packages
      
    - name: Generate output
      run: make generate-output
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: live-script # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
    
